- id: pydantic-settings-export
  name: pydantic-settings-export
  description: "Export your Pydantic settings to Markdown and .env.example files!"
  entry: pydantic-settings-export
  language: python
  files: \.py$
  args: [ ]
  pass_filenames: false
  additional_dependencies: [ ]
  stages: [ pre-commit ]
